version: '3.3'
services:
  pythonapp:
    build: ./python/
    container_name: python_motor_run
    entrypoint: /bin/sh
    stdin_open: true
    volumes:
      - ./python/:/code
    depends_on:
      - postgres
  postgres:
    build: ./postgres/
    container_name: postgres_motor_run
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/volume/:/var/lib/postgresql/data

    